### PR TITLE
compatible with c++11, add font scale

### PR DESCRIPTION
**Pull request by Xrysnow**

### CODE REVIEW

**Comment by juliettef** [comment]
imgui_markdown requires C++14 due to the use of [aggregate initializers along with default member initializers](https://en.cppreference.com/w/cpp/language/aggregate_initialization). Adding C++11 constructors would break our users' code in a way that would be difficult to workaround and adding initializer list constructors is somewhat of a pain.

Regarding the font size we would prefer not to use font scaling as it's not very high quality but we are considering adding a way to allow users to set the font parameters though a function callback.

**Comment by juliettef** [comment]
Forgot to say many thanks for the PR. It's helped a lot with improving the code.

**Comment by juliettef** [comment]
Submitted [question regarding C++11 support](https://github.com/juliettef/imgui_markdown/issues/10#issue-674406406)

**Comment by dougbinks** [comment]
We've updated the code with backwards compatible C++11 support, and will look into supporting font parameters through a function callback later on.

**Comment by juliettef** [comment]
See #13 for solution to font scale

**Pull request closed without merging**
